### ISSUE TITLE
Request a permission to include this in my module.

### ISSUE THREAD

**Issue by CrescendoFang** [Magisk-Modules-Repo/navbar-overlay#1]
Hi friend, may I include this to my module?
https://github.com/Magisk-Modules-Repo/natrium-mods

Your module fixed the broken whitelist problem with some MIUI ROMs.

Thank you so much.

**Comment by null4n** [comment]
Yes you're welcome. BTW you'd add a script to remove "qemu.hw.mainkeys"
property. Just "resetprop --delete qemu.hw.mainkeys". some ROM has this
property to override the navigation bar config. I'll add this later on my
repo too.

**Comment by CrescendoFang** [comment]
ah, so those "qemu.hw.mainkeys" no longer needed in the build.prop?

Thanks a lot, I 'll credit you in the readme ^^

**Comment by null4n** [comment]
yep, the "qemu.hw.mainkeys" will force override navigation bar config. so
we don't need it anymore.
